matlab_add_mex(NAME slide_mex SRC slide_mex.cpp R2018a)
target_link_libraries(slide_mex slide_core)
target_compile_features(slide_mex PRIVATE cxx_std_20)
set_target_properties(slide_mex PROPERTIES
  LIBRARY_OUTPUT_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
  RUNTIME_OUTPUT_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
  RUNTIME_OUTPUT_DIRECTORY_DEBUG "${CMAKE_CURRENT_SOURCE_DIR}"
  RUNTIME_OUTPUT_DIRECTORY_RELEASE "${CMAKE_CURRENT_SOURCE_DIR}"
  RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO "${CMAKE_CURRENT_SOURCE_DIR}"
  RUNTIME_OUTPUT_DIRECTORY_MINSIZEREL "${CMAKE_CURRENT_SOURCE_DIR}")

install(TARGETS slide_mex
  LIBRARY DESTINATION matlab
  RUNTIME DESTINATION matlab)
install(DIRECTORY +slide DESTINATION matlab)
