title: SLIDE
description: Official documentation of SLIDE software.
url: https://battery-intelligence-lab.github.io
baseurl: /SLIDE
remote_theme: Battery-Intelligence-Lab/bil-jekyll-rtd-theme@640a185d7819012d804945832cd9d3edcd7336ca
repository: Battery-Intelligence-Lab/SLIDE
plugins:
  - jekyll-remote-theme
  - jekyll-github-metadata
github:
  source:
    branch: master
    path: docs
