# project-specific settings.

# set(PROJECT_NAME "SLIDE")

# set(PROJECT_MAJOR_VERSION 3)
# set(PROJECT_MINOR_VERSION 0)
# set(PROJECT_PATCH_VERSION 0)
# set(PROJECT_VERSION
#   ${PROJECT_MAJOR_VERSION}.${PROJECT_MINOR_VERSION}.${PROJECT_PATCH_VERSION})

