name: Windows unit
# adapted from: https://github.com/trase-cpp/trase/tree/master/.github/workflows
on:
  push:
    branches:
      - master
      - data_storage
  pull_request:
    branches:
      - '**'

jobs:

  build-and-test:
    name: Windows unit
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: make build directory
        run: mkdir build_dir

      - name: cmake configure
        run: cmake .. -DCMAKE_BUILD_TYPE=Debug
        working-directory: build_dir

      - name: cmake build
        run: cmake --build . --parallel 2
        working-directory: build_dir

      - name: cmake test
        run: ctest -j1 -C Debug --verbose --output-on-failure
        working-directory: build_dir
